name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - P0 - Critical (MVP blocker)
        - P1 - High (important for launch)
        - P2 - Medium (nice to have)
        - P3 - Low (future consideration)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Which area does this feature relate to?
      options:
        - User-Facing (Customer Experience)
        - Admin Panel
        - Performance
        - Security
        - Developer Experience
        - Infrastructure
        - Analytics
        - Other
      multiple: true
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: As a [user type], I want to [goal] so that [benefit]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How do we know when this feature is complete?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any mockups, diagrams, or examples
    validations:
      required: false

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Duplicate Check
      description: Have you searched for existing issues?
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
