<template>
  <component :is="resolvedIcon" v-bind="$attrs" />
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { Component } from 'vue'
import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  BadgeDollarSign,
  Ban,
  Banknote,
  BarChart2,
  Bell,
  Box,
  Boxes,
  Building2,
  CalendarDays,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  CircleHelp,
  CircleX,
  ClipboardList,
  Clock,
  CreditCard,
  Euro,
  Eye,
  Filter,
  FlaskConical,
  Gift,
  Globe2,
  Hand,
  Heart,
  Home,
  Info,
  Key,
  LayoutDashboard,
  LifeBuoy,
  Lightbulb,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  MapPin,
  Megaphone,
  Menu,
  Minus,
  Monitor,
  MoreVertical,
  MousePointerClick,
  Package,
  PanelsTopLeft,
  Pause,
  Pencil,
  Phone,
  Play,
  Plus,
  Radar,
  RefreshCcw,
  Search,
  Send,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  SquarePen,
  Star,
  Trash2,
  TrendingUp,
  Truck,
  User,
  UserPlus,
  Users,
  Wallet,
  Wrench,
  X
} from 'lucide-vue-next'

const props = defineProps<{ name: string }>()

const ICONS: Record<string, Component> = {
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-trending-up': TrendingUp,
  'arrow-up-right': ArrowUpRight,
  'arrow-path': RefreshCcw,
  'arrow-right-on-rectangle': LogOut,
  'arrow-left-on-rectangle': LogIn,
  'banknote': Banknote,
  'banknotes': Banknote,
  'bar-chart-2': BarChart2,
  'chart-bar': BarChart2,
  'badge-check': BadgeCheck,
  'badge-dollar-sign': BadgeDollarSign,
  'ban': Ban,
  'bell': Bell,
  'building-2': Building2,
  'building-library': Building2,
  'calendar-days': CalendarDays,
  'camera': Camera,
  'check': Check,
  'check-badge': BadgeCheck,
  'check-circle': CheckCircle2,
  'check-circle-2': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-up-down': ChevronsUpDown,
  'circle-help': CircleHelp,
  'question-mark-circle': CircleHelp,
  'circle-x': CircleX,
  'x-circle': CircleX,
  'clipboard-document': ClipboardList,
  'clipboard-list': ClipboardList,
  'clock': Clock,
  'credit-card': CreditCard,
  'cube': Box,
  'cube-transparent': Boxes,
  'cursor-click': MousePointerClick,
  'currency-euro': Euro,
  'device-phone-mobile': Smartphone,
  'ellipsis-vertical': MoreVertical,
  'exclamation-circle': AlertCircle,
  'eye': Eye,
  'filter': Filter,
  'funnel': Filter,
  'flask-conical': FlaskConical,
  'beaker': FlaskConical,
  'gift': Gift,
  'gift-top': Gift,
  'globe-2': Globe2,
  'globe-alt': Globe2,
  'hand': Hand,
  'hand-raised': Hand,
  'heart': Heart,
  'home': Home,
  'information-circle': Info,
  'info': Info,
  'key': Key,
  'layout-dashboard': LayoutDashboard,
  'life-buoy': LifeBuoy,
  'light-bulb': Lightbulb,
  'lightbulb': Lightbulb,
  'loader-2': Loader2,
  'lock': Lock,
  'lock-closed': Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  'magnifying-glass': Search,
  'map-pin': MapPin,
  'package': Package,
  'megaphone': Megaphone,
  'menu': Menu,
  'bars-3': Menu,
  'minus': Minus,
  'monitor': Monitor,
  'more-vertical': MoreVertical,
  'paper-airplane': Send,
  'pause': Pause,
  'pencil': Pencil,
  'pencil-square': SquarePen,
  'phone': Phone,
  'play': Play,
  'plus': Plus,
  'question-circle': CircleHelp,
  'radar': Radar,
  'refresh-ccw': RefreshCcw,
  'arrow-path-refresh': RefreshCcw,
  'search': Search,
  'send': Send,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'smartphone': Smartphone,
  'sparkles': Sparkles,
  'squares-2x2': PanelsTopLeft,
  'panels-top-left': PanelsTopLeft,
  'square-pen': SquarePen,
  'star': Star,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  'triangle-alert': AlertTriangle,
  'truck': Truck,
  'user': User,
  'user-plus': UserPlus,
  'users': Users,
  'wallet': Wallet,
  'wrench': Wrench,
  'x': X,
  'x-mark': X,
  'alert-octagon': AlertTriangle,
  'alert': AlertTriangle
}

const fallbackIcon = CircleHelp

const resolvedIcon = computed<Component>(() => {
  const raw = props.name?.trim()
  if (!raw) {
    return fallbackIcon
  }

  let key = raw.replace(/\s+/g, '-').replace(/_/g, '-').toLowerCase()

  if (key.startsWith('simple-icons:')) {
    return ICONS[key] ?? fallbackIcon
  }

  key = key
    .replace(/^lucide:/, '')
    .replace(/^heroicons:/, '')

  return ICONS[key] ?? fallbackIcon
})
</script>
