#!/bin/bash

# Screenshot Capture Helper Script
# Moldova Direct - Final Validation

SCREENSHOT_DIR="/Users/vladislavcaraseli/Documents/MoldovaDirect/checkout-ux-testing/screenshots/final-validation"

echo "=========================================="
echo "Moldova Direct - Screenshot Capture Guide"
echo "=========================================="
echo ""
echo "This script will help you capture validation screenshots."
echo ""
echo "Screenshot directory: $SCREENSHOT_DIR"
echo ""

# Open the products page in browser
echo "Step 1: Opening products page in Chrome..."
open -a "Google Chrome" "http://localhost:3000/products"
echo ""
echo "✓ Products page opened"
echo ""
echo "ACTION REQUIRED:"
echo "  1. Wait for page to fully load (products should be visible)"
echo "  2. Take a screenshot (Cmd+Shift+4 or Cmd+Shift+3)"
echo "  3. Save as: $SCREENSHOT_DIR/products-page-SUCCESS.png"
echo ""
read -p "Press Enter when screenshot is saved..."

echo ""
echo "=========================================="
echo "Step 2: Add to Cart Test"
echo "=========================================="
echo ""
echo "ACTION REQUIRED:"
echo "  1. On the products page, click 'Añadir al Carrito' on any product"
echo "  2. Observe cart icon update (should show item count)"
echo "  3. Take a screenshot showing the updated cart"
echo "  4. Save as: $SCREENSHOT_DIR/add-to-cart-SUCCESS.png"
echo ""
read -p "Press Enter when screenshot is saved..."

echo ""
echo "=========================================="
echo "Step 3: Cart Page Test"
echo "=========================================="
echo ""
echo "Opening cart page..."
open -a "Google Chrome" "http://localhost:3000/cart"
echo ""
echo "ACTION REQUIRED:"
echo "  1. Wait for cart page to load"
echo "  2. Verify your added product(s) are visible"
echo "  3. Take a screenshot of the cart page"
echo "  4. Save as: $SCREENSHOT_DIR/cart-page-SUCCESS.png"
echo ""
read -p "Press Enter when screenshot is saved..."

echo ""
echo "=========================================="
echo "Step 4: Checkout Flow Test"
echo "=========================================="
echo ""
echo "ACTION REQUIRED:"
echo "  1. From the cart page, click the 'Checkout' button"
echo "  2. Wait for shipping form to load"
echo "  3. Take a screenshot of the checkout/shipping page"
echo "  4. Save as: $SCREENSHOT_DIR/checkout-shipping-SUCCESS.png"
echo ""
read -p "Press Enter when screenshot is saved..."

echo ""
echo "=========================================="
echo "✓ Screenshot capture process complete!"
echo "=========================================="
echo ""
echo "Verification:"
echo "Please check that all 4 screenshots exist:"
echo "  1. products-page-SUCCESS.png"
echo "  2. add-to-cart-SUCCESS.png"
echo "  3. cart-page-SUCCESS.png"
echo "  4. checkout-shipping-SUCCESS.png"
echo ""
echo "Location: $SCREENSHOT_DIR"
echo ""
echo "Next step: Review FINAL_VALIDATION.md report"
echo ""
